tipo_serviço = ['Alinhar Direção',
                'Auto Diagnóstico',
                'Carregar A/C',
                'Carregar A/C- Campanha',
                'Desmontar e Montar FAP',
                'Equilibrar Rodas',
                'Higienização - Campanha FD',
                'Inspecionar Travões',
                'IPO', 
                'Lavar e Aspirar', 
                'Limpeza do Circuito de Alimentação',
                'Medir Compressão',
                'Medir Retorno de Injetores',
                'Mudar Óleo', 
                'Mudar Óleo e Filtro de Óleo',
                'Polir Óticas',
                'Preparar para IPO + IP',
                'Reconfiguração Softwar',
                'Reparar Bomba Injectora',
                'Reparar Culaça',
                'Reparar Fugas de Compressão',
                'Reparar Furo Pneu',
                'Reparar Injectores',
                'Reparar Motor',
                'Reparar Sistema de A/C',
                'Reparar Turbo',
                'Revisão + Higienização  - Camapnha FD',
                'Revisão 111 - Campanha FD',
                'Revisão Geral',
                'Serviço de Colisão ',
                'Serviço de Pintura',
                'Subst. Amortecedores',
                'Subst. Bielete de Direção',
                'Subst. Braços de Suspensão',
                'Subst. Casquilhos Barra Estabelizadora',
                'Subst. Compressor de A/C',
                'Subst. Condensador A/C',
                'Subst. Correia Auxiliar',
                'Subst. EGR',
                'Subst. Embraiagem',
                'Subst. FAP',
                'Subst. Filtro de Ar',
                'Subst. Filtro de Combustivel',
                'Subst. Filtro de Habitáculo',
                'Subst. Kit Distribuição',
                'Subst. Kit Distribuição C/Bomba de Água',
                'Subst. Óleo de Travões',
                'Subst. Pastilhas de Travão Frt',
                'Subst. Pastilhas de Travão Frt / Trás',
                'Subst. Pastilhas de Travão Trás',
                'Subst. Pneus Frt',
                'Subst. Pneus Frt / Trás',
                'Subst. Pneus Tras',
                'Subst. Ponteiras de Direção',
                'Subst. Radiador de Água',
                'Subst. Rolamento Roda Frt',
                'Subst. Rolamento Roda Frt / Trás',
                'Subst. Rolamento Roda Trás',
                'Subst. Rotulas de Suspensão',
                'Subst. Tensor',
                'Subst. Tirantes Barra Estabelizadora',
                'Subst. Tubo de Admissão',
                'Subst. Velas',
                'Verificações Gerais',
                'Verif. Alimentação',
                'Verif. Barulho ',
                'Verif. Barulho Correia Auxiliar',
                'Verif. Barulho Travões Frt',
                'Verif. Barulho Travões Trás',
                'Verif. Luz ABS',
                'Verif. Luz AirBag',
                'Verif. Luz de Avaria Acesa',
                'Verif. Luz do Motor Acesa',
                'Verif. niveis e Luzes',
                'Verif. viatura Pega Mal',]